kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-psp
  namespace: che
subjects:
  - kind: ServiceAccount
    name: che-workspace
    namespace: che
roleRef:
  kind: ClusterRole
  name: ibm-anyuid-hostpath-clusterrole
  apiGroup: rbac.authorization.k8s.io
